name: Update compat symbols

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: purcell/setup-emacs@master
      with:
        version: 28.2
    - run: tools/compat-dump
    - uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Regenerate compat symbols
        file_pattern: data/compat-symbols
