name: Update stdlib-changes

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
    - run: tools/sym-dump-all
    - uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Regenerate stdlib-changes
        file_pattern: data/stdlib-changes
